# Generated by Django 5.0.6 on 2024-07-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'league'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'tournament'},
        ),
        migrations.AddField(
            model_name='league',
            name='coalition_allowed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='coalition allowed'),
        ),
        migrations.AddField(
            model_name='league',
            name='max_players_per_game',
            field=models.IntegerField(blank=True, default=6, null=True, verbose_name='maximum number of players per game'),
        ),
        migrations.AddField(
            model_name='league',
            name='min_players_per_game',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='minimum number of players per game'),
        ),
        migrations.AddField(
            model_name='league',
            name='three_coalition_allowed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='three way coalition allowed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='coalition_allowed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='coalition allowed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players_per_game',
            field=models.IntegerField(blank=True, default=6, null=True, verbose_name='maximum number of players per game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_players_per_game',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='minimum number of players per game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='three_coalition_allowed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='three way coalition allowed'),
        ),
    ]
