# Generated by Django 5.0.6 on 2024-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_league_options_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='coalition_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='coalition allowed'),
        ),
        migrations.AlterField(
            model_name='league',
            name='max_players_per_game',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum number of players per game'),
        ),
        migrations.AlterField(
            model_name='league',
            name='min_players_per_game',
            field=models.IntegerField(blank=True, null=True, verbose_name='minimum number of players per game'),
        ),
        migrations.AlterField(
            model_name='league',
            name='three_coalition_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='three way coalition allowed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='coalition_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='coalition allowed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_players_per_game',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum number of players per game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_players_per_game',
            field=models.IntegerField(blank=True, null=True, verbose_name='minimum number of players per game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='three_coalition_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='three way coalition allowed'),
        ),
    ]
