# Generated by Django 5.0.6 on 2024-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_league_coalition_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='coalition_score_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='coalition score multiplier'),
        ),
        migrations.AddField(
            model_name='league',
            name='total_score_per_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='total score per game'),
        ),
        migrations.AddField(
            model_name='league',
            name='win_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='win score'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='coalition_score_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='coalition score multiplier'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_score_per_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='total score per game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='win_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='win score'),
        ),
    ]
