# Generated by Django 5.0.6 on 2024-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_league_coalition_score_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='board_map',
            field=models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('mountain', 'Mountain'), ('lake', 'Lake')], max_length=20, verbose_name='map'),
        ),
        migrations.AddField(
            model_name='league',
            name='deck',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('e&p', 'Exiles and Partisans')], max_length=200, verbose_name='deck'),
        ),
        migrations.AddField(
            model_name='league',
            name='game_setup',
            field=models.CharField(blank=True, choices=[('adset', 'Advanced'), ('standard', 'Standard')], max_length=20, verbose_name='setup'),
        ),
        migrations.AddField(
            model_name='league',
            name='random_suits',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='random suits'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='board_map',
            field=models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('mountain', 'Mountain'), ('lake', 'Lake')], max_length=20, verbose_name='map'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='deck',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('e&p', 'Exiles and Partisans')], max_length=200, verbose_name='deck'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game_setup',
            field=models.CharField(blank=True, choices=[('adset', 'Advanced'), ('standard', 'Standard')], max_length=20, verbose_name='setup'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='random_suits',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='random suits'),
        ),
    ]
