# Generated by Django 5.0.6 on 2024-08-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_league_random_suits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_is_default'),
        ),
    ]
