# Generated by Django 5.0.6 on 2024-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_league_is_default_league_unique_is_default'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='league',
            name='unique_is_default',
        ),
        migrations.AddField(
            model_name='league',
            name='min_games',
            field=models.IntegerField(blank=True, help_text='For leaderboards.', null=True, verbose_name='minimum number of games'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_games',
            field=models.IntegerField(blank=True, help_text='For leaderboards.', null=True, verbose_name='minimum number of games'),
        ),
    ]
