# Generated by Django 5.0.6 on 2024-08-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_league_unique_is_default_league_min_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='min_games',
            field=models.IntegerField(blank=True, help_text='Threshold for leaderboards.', null=True, verbose_name='minimum number of games'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_games',
            field=models.IntegerField(blank=True, help_text='Threshold for leaderboards.', null=True, verbose_name='minimum number of games'),
        ),
    ]
