# Generated by Django 5.1.1 on 2025-01-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_alter_league_min_games_alter_tournament_min_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='stats_display',
            field=models.BooleanField(default=False, verbose_name='displayed in stats'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stats_display',
            field=models.BooleanField(default=False, verbose_name='displayed in stats'),
        ),
    ]
