# Generated by Django 5.2.7 on 2025-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_league_stats_display_tournament_stats_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='hirelings_allowed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='hirelings allowed'),
        ),
        migrations.AddField(
            model_name='league',
            name='landmarks_allowed',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], default=0, null=True, verbose_name='landmarks allowed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='hirelings_allowed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='hirelings allowed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='landmarks_allowed',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], default=0, null=True, verbose_name='landmarks allowed'),
        ),
    ]
