# Generated by Django 5.2.7 on 2025-12-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_league_hirelings_allowed_league_landmarks_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='hirelings_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='hirelings allowed'),
        ),
        migrations.AlterField(
            model_name='league',
            name='landmarks_allowed',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], null=True, verbose_name='landmarks allowed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='hirelings_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='hirelings allowed'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='landmarks_allowed',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], null=True, verbose_name='landmarks allowed'),
        ),
    ]
