# Generated by Django 5.2.7 on 2025-12-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_league_hirelings_allowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='hirelings_allowed',
            new_name='hirelings',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='landmarks_allowed',
            new_name='landmarks_required',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='hirelings_allowed',
            new_name='hirelings',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='landmarks_allowed',
            new_name='landmarks_required',
        ),
        migrations.AlterField(
            model_name='league',
            name='hirelings',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='landmarks_required',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='hirelings',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='landmarks_required',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], null=True),
        ),
    ]
