# Generated by Django 5.2.7 on 2026-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_remove_league_hirelings_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='public',
            field=models.BooleanField(default=True, help_text='Public RDL league or tournament.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=True, help_text='Public RDL league or tournament.'),
        ),
    ]
