# Generated by Django 5.2.7 on 2026-01-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_league_public_tournament_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='public',
            field=models.BooleanField(default=False, help_text='Public RDL league or tournament.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=False, help_text='Public RDL league or tournament.'),
        ),
    ]
