# Generated by Django 5.2.7 on 2026-01-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_alter_league_public_alter_tournament_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='stats_display',
            new_name='visibility',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='stats_display',
            new_name='visibility',
        ),
        migrations.AlterField(
            model_name='league',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='visibility'),
        ),
    ]
