# Generated by Django 3.0.3 on 2023-01-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_participant_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyre Dynasties'), ('alliance', 'Woodland Alliance'), ('vagabond', 'Vagabond'), ('otters', 'Riverfolk'), ('lizards', 'Lizard Cult')], max_length=100, null=True),
        ),
    ]
