# Generated by Django 4.1 on 2024-06-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchmaking', '0004_auto_20230111_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='random_suits',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='map',
            field=models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('mountain', 'Mountain'), ('lake', 'Lake')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='dominance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond: Ranger'), ('vb_thief', 'Vagabond: Thief'), ('vb_tinker', 'Vagabond: Tinker'), ('vb_vagrant', 'Vagabond: Vagrant'), ('vb_arbiter', 'Vagabond: Arbiter'), ('vb_scoundrel', 'Vagabond: Scoundrel'), ('vb_adventurer', 'Vagabond: Adventurer'), ('vb_ronin', 'Vagabond: Ronin'), ('vb_harrier', 'Vagabond: Harrier')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='winner',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
