# Generated by Django 4.1 on 2024-06-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_match_random_suits_alter_match_closed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='map',
            new_name='board_map',
        ),
    ]
