# Generated by Django 5.0.6 on 2024-07-02 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_rename_map_match_board_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='coalition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmaking.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dominance',
            field=models.CharField(blank=True, choices=[('bird', 'Bird dominance'), ('fox', 'Fox dominance'), ('mouse', 'Mouse dominance'), ('rabbit', 'Rabbit dominance')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
