# Generated by Django 5.0.6 on 2024-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_alter_participant_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='closed',
            field=models.BooleanField(default=True),
        ),
    ]
