# Generated by Django 5.0.6 on 2024-07-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0009_alter_match_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at']},
        ),
    ]
