# Generated by Django 5.0.6 on 2024-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0011_alter_match_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='winner',
        ),
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.DecimalField(blank=True, choices=[(1.0, 1), (0.5, 0.5), (0.0, 0)], decimal_places=1, max_digits=10, null=True),
        ),
    ]
