# Generated by Django 5.0.6 on 2024-07-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0013_participant_league_score_alter_participant_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='score',
            new_name='game_score',
        ),
    ]
