# Generated by Django 5.0.6 on 2024-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0014_rename_score_participant_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='deck',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('e&p', 'Exiles and Partisans')], default='e&p', max_length=200),
        ),
    ]
