# Generated by Django 5.0.6 on 2024-07-13 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0016_alter_match_board_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='board_map',
            field=models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('mountain', 'Mountain'), ('lake', 'Lake')], max_length=20, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='closed',
            field=models.BooleanField(db_default=True, default=True, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='match',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='closure_date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registration_date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='deck',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('e&p', 'Exiles and Partisans')], default='e&p', max_length=200, verbose_name='deck'),
        ),
        migrations.AlterField(
            model_name='match',
            name='random_suits',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='random suits'),
        ),
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='coalition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmaking.participant', verbose_name='coalition'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dominance',
            field=models.CharField(blank=True, choices=[('bird', 'Bird dominance'), ('fox', 'Fox dominance'), ('mouse', 'Mouse dominance'), ('rabbit', 'Rabbit dominance')], max_length=100, verbose_name='dominance'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond: Ranger'), ('vb_thief', 'Vagabond: Thief'), ('vb_tinker', 'Vagabond: Tinker'), ('vb_vagrant', 'Vagabond: Vagrant'), ('vb_arbiter', 'Vagabond: Arbiter'), ('vb_scoundrel', 'Vagabond: Scoundrel'), ('vb_adventurer', 'Vagabond: Adventurer'), ('vb_ronin', 'Vagabond: Ronin'), ('vb_harrier', 'Vagabond: Harrier')], max_length=100, verbose_name='faction'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='game_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='game score'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='league_score',
            field=models.DecimalField(blank=True, choices=[(1.0, 1), (0.5, 0.5), (0.0, 0)], decimal_places=1, max_digits=2, null=True, verbose_name='league score'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matchmaking.match', verbose_name='match'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='turn_order',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='turn order'),
        ),
    ]
