# Generated by Django 5.0.6 on 2024-07-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0018_alter_match_closed_at_alter_match_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_registered']},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='closed_at',
            new_name='date_closed',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='created_at',
            new_name='date_registered',
        ),
    ]
