# Generated by Django 5.0.6 on 2024-07-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0023_alter_match_board_map_alter_match_table_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='league',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
