# Generated by Django 5.0.6 on 2024-07-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('matchmaking', '0024_remove_tournament_league_remove_match_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='league.tournament', verbose_name='tournament'),
        ),
    ]
