# Generated by Django 5.0.6 on 2024-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0026_alter_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table_talk_url',
            field=models.URLField(blank=True, help_text='e.g. Discord thread', null=True, verbose_name='table talk url'),
        ),
    ]
