# Generated by Django 5.0.6 on 2024-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0027_match_table_talk_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_setup',
            field=models.CharField(blank=True, choices=[('adset', 'Advanced'), ('standard', 'Standard')], default='adset', max_length=20, verbose_name='setup'),
        ),
        migrations.AddField(
            model_name='match',
            name='undrafted_faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond: Ranger'), ('vb_thief', 'Vagabond: Thief'), ('vb_tinker', 'Vagabond: Tinker'), ('vb_vagrant', 'Vagabond: Vagrant'), ('vb_arbiter', 'Vagabond: Arbiter'), ('vb_scoundrel', 'Vagabond: Scoundrel'), ('vb_adventurer', 'Vagabond: Adventurer'), ('vb_ronin', 'Vagabond: Ronin'), ('vb_harrier', 'Vagabond: Harrier')], help_text='Only in advanced setup.', max_length=100, verbose_name='undrafted faction'),
        ),
        migrations.AlterField(
            model_name='match',
            name='table_talk_url',
            field=models.URLField(blank=True, help_text='E.g. Discord thread.', null=True, verbose_name='table talk URL'),
        ),
    ]
