# Generated by Django 5.0.6 on 2024-07-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0028_match_game_setup_match_undrafted_faction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_registered'], 'verbose_name': 'match'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'participant'},
        ),
    ]
