# Generated by Django 5.0.6 on 2024-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0029_alter_match_options_alter_participant_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='league_score',
            new_name='tournament_score',
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament_score',
            field=models.DecimalField(blank=True, choices=[(1.0, 1), (0.5, 0.5), (0.0, 0)], decimal_places=1, max_digits=2, null=True, verbose_name='tournament score'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='turn_order',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True, verbose_name='turn order'),
        ),
    ]
