# Generated by Django 5.0.6 on 2024-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0030_remove_participant_league_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='board_map',
            field=models.CharField(choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('mountain', 'Mountain'), ('lake', 'Lake')], default='autumn', max_length=20, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='deck',
            field=models.CharField(choices=[('standard', 'Standard'), ('e&p', 'Exiles and Partisans')], default='e&p', max_length=200, verbose_name='deck'),
        ),
        migrations.AlterField(
            model_name='match',
            name='undrafted_faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond (Ranger)'), ('vb_thief', 'Vagabond (Thief)'), ('vb_tinker', 'Vagabond (Tinker)'), ('vb_vagrant', 'Vagabond (Vagrant)'), ('vb_arbiter', 'Vagabond (Arbiter)'), ('vb_scoundrel', 'Vagabond (Scoundrel)'), ('vb_adventurer', 'Vagabond (Adventurer)'), ('vb_ronin', 'Vagabond (Ronin)'), ('vb_harrier', 'Vagabond (Harrier)')], help_text='Only in advanced setup.', max_length=100, verbose_name='undrafted faction'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='faction',
            field=models.CharField(choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond (Ranger)'), ('vb_thief', 'Vagabond (Thief)'), ('vb_tinker', 'Vagabond (Tinker)'), ('vb_vagrant', 'Vagabond (Vagrant)'), ('vb_arbiter', 'Vagabond (Arbiter)'), ('vb_scoundrel', 'Vagabond (Scoundrel)'), ('vb_adventurer', 'Vagabond (Adventurer)'), ('vb_ronin', 'Vagabond (Ronin)'), ('vb_harrier', 'Vagabond (Harrier)')], max_length=100, verbose_name='faction'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament_score',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='tournament score'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='turn_order',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True, verbose_name='turn order'),
        ),
    ]
