# Generated by Django 5.0.6 on 2024-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0031_alter_match_board_map_alter_match_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='board_map',
            field=models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('mountain', 'Mountain'), ('lake', 'Lake')], default='autumn', max_length=20, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='deck',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('e&p', 'Exiles and Partisans')], default='e&p', max_length=200, verbose_name='deck'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond (Ranger)'), ('vb_thief', 'Vagabond (Thief)'), ('vb_tinker', 'Vagabond (Tinker)'), ('vb_vagrant', 'Vagabond (Vagrant)'), ('vb_arbiter', 'Vagabond (Arbiter)'), ('vb_scoundrel', 'Vagabond (Scoundrel)'), ('vb_adventurer', 'Vagabond (Adventurer)'), ('vb_ronin', 'Vagabond (Ronin)'), ('vb_harrier', 'Vagabond (Harrier)')], max_length=100, verbose_name='faction'),
        ),
    ]
