# Generated by Django 5.0.6 on 2024-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0033_alter_participant_tournament_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='table_talk',
            new_name='turn_timing',
        ),
    ]
