# Generated by Django 5.1.1 on 2024-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0034_remove_match_table_talk_match_turn_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='turn_timing',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('async', 'Async')], default='async', max_length=20, verbose_name='turn timing'),
        ),
    ]
