# Generated by Django 5.1.1 on 2024-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0035_alter_match_turn_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='table_talk_url',
            field=models.URLField(blank=True, help_text='E.g. Discord thread.', max_length=1000, null=True, verbose_name='table talk URL'),
        ),
    ]
