# Generated by Django 5.1.1 on 2024-12-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0036_alter_match_table_talk_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='undrafted_faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk Company'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond (Ranger)'), ('vb_thief', 'Vagabond (Thief)'), ('vb_tinker', 'Vagabond (Tinker)'), ('vb_vagrant', 'Vagabond (Vagrant)'), ('vb_arbiter', 'Vagabond (Arbiter)'), ('vb_scoundrel', 'Vagabond (Scoundrel)'), ('vb_adventurer', 'Vagabond (Adventurer)'), ('vb_ronin', 'Vagabond (Ronin)'), ('vb_harrier', 'Vagabond (Harrier)')], help_text='Only in advanced setup.', max_length=100, verbose_name='undrafted faction'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='faction',
            field=models.CharField(blank=True, choices=[('cats', 'Marquise de Cat'), ('birds', 'Eyrie Dynasties'), ('alliance', 'Woodland Alliance'), ('otters', 'Riverfolk Company'), ('lizards', 'Lizard Cult'), ('moles', 'Underground Duchy'), ('crows', 'Corvid Conspiracy'), ('rats', 'Lord of the Hundreds'), ('badgers', 'Keepers in Iron'), ('vb_ranger', 'Vagabond (Ranger)'), ('vb_thief', 'Vagabond (Thief)'), ('vb_tinker', 'Vagabond (Tinker)'), ('vb_vagrant', 'Vagabond (Vagrant)'), ('vb_arbiter', 'Vagabond (Arbiter)'), ('vb_scoundrel', 'Vagabond (Scoundrel)'), ('vb_adventurer', 'Vagabond (Adventurer)'), ('vb_ronin', 'Vagabond (Ronin)'), ('vb_harrier', 'Vagabond (Harrier)')], max_length=100, verbose_name='faction'),
        ),
    ]
