# Generated by Django 5.1.1 on 2025-01-01 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0038_alter_match_options_match_date_modified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='tournament score'),
        ),
    ]
