# Generated by Django 5.1.1 on 2025-08-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0039_alter_match_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='coalition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coalitioned_vagabond', to='matchmaking.participant', verbose_name='coalition'),
        ),
    ]
