# Generated by Django 5.1.1 on 2025-10-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0040_alter_participant_coalition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='board_map',
            field=models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('mountain', 'Mountain'), ('lake', 'Lake')], max_length=20, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='match',
            name='random_suits',
            field=models.BooleanField(blank=True, null=True, verbose_name='random suits'),
        ),
    ]
