# Generated by Django 5.2.7 on 2025-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0041_alter_match_board_map_alter_match_random_suits'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hirelings_a',
            field=models.CharField(blank=True, choices=[('h_badgers_p', 'Vault Keepers'), ('h_badgers_d', 'Badger Bodyguards'), ('h_band_p', 'Popular Band'), ('h_band_d', 'Street Band'), ('h_bandits_p', 'Highway Bandits'), ('h_bandits_d', 'Bandit Gangs'), ('h_crows_p', 'Corvid Spies'), ('h_crows_d', 'Raven Sentries'), ('h_lizards_p', 'Warm Sun Prophets'), ('h_lizards_d', 'Lizard Envoys'), ('h_moles_p', 'Warm Sun Prophets'), ('h_moles_d', 'Lizard Envoys'), ('h_birds_p', 'Last Dynasty'), ('h_birds_d', 'Bluebird Nobles'), ('h_cats_p', 'Forest Patrol'), ('h_cats_d', 'Feline Physicians'), ('h_protector_p', 'Furious Protector'), ('h_protector_d', 'Stoic Protector'), ('h_rats_p', 'Flame Bearers'), ('h_rats_d', 'Rat Smugglers'), ('h_otters_p', 'Riverfolk Flotilla'), ('h_otters_d', 'Otter Divers'), ('h_vb_p', 'The Exile'), ('h_vb_d', 'The Brigand'), ('h_alliance_p', 'Spring Uprising'), ('h_alliance_d', 'Rabbit Scouts')], max_length=200, verbose_name='hirelings'),
        ),
        migrations.AddField(
            model_name='match',
            name='hirelings_b',
            field=models.CharField(blank=True, choices=[('h_badgers_p', 'Vault Keepers'), ('h_badgers_d', 'Badger Bodyguards'), ('h_band_p', 'Popular Band'), ('h_band_d', 'Street Band'), ('h_bandits_p', 'Highway Bandits'), ('h_bandits_d', 'Bandit Gangs'), ('h_crows_p', 'Corvid Spies'), ('h_crows_d', 'Raven Sentries'), ('h_lizards_p', 'Warm Sun Prophets'), ('h_lizards_d', 'Lizard Envoys'), ('h_moles_p', 'Warm Sun Prophets'), ('h_moles_d', 'Lizard Envoys'), ('h_birds_p', 'Last Dynasty'), ('h_birds_d', 'Bluebird Nobles'), ('h_cats_p', 'Forest Patrol'), ('h_cats_d', 'Feline Physicians'), ('h_protector_p', 'Furious Protector'), ('h_protector_d', 'Stoic Protector'), ('h_rats_p', 'Flame Bearers'), ('h_rats_d', 'Rat Smugglers'), ('h_otters_p', 'Riverfolk Flotilla'), ('h_otters_d', 'Otter Divers'), ('h_vb_p', 'The Exile'), ('h_vb_d', 'The Brigand'), ('h_alliance_p', 'Spring Uprising'), ('h_alliance_d', 'Rabbit Scouts')], max_length=200, verbose_name='hirelings bis'),
        ),
        migrations.AddField(
            model_name='match',
            name='hirelings_c',
            field=models.CharField(blank=True, choices=[('h_badgers_p', 'Vault Keepers'), ('h_badgers_d', 'Badger Bodyguards'), ('h_band_p', 'Popular Band'), ('h_band_d', 'Street Band'), ('h_bandits_p', 'Highway Bandits'), ('h_bandits_d', 'Bandit Gangs'), ('h_crows_p', 'Corvid Spies'), ('h_crows_d', 'Raven Sentries'), ('h_lizards_p', 'Warm Sun Prophets'), ('h_lizards_d', 'Lizard Envoys'), ('h_moles_p', 'Warm Sun Prophets'), ('h_moles_d', 'Lizard Envoys'), ('h_birds_p', 'Last Dynasty'), ('h_birds_d', 'Bluebird Nobles'), ('h_cats_p', 'Forest Patrol'), ('h_cats_d', 'Feline Physicians'), ('h_protector_p', 'Furious Protector'), ('h_protector_d', 'Stoic Protector'), ('h_rats_p', 'Flame Bearers'), ('h_rats_d', 'Rat Smugglers'), ('h_otters_p', 'Riverfolk Flotilla'), ('h_otters_d', 'Otter Divers'), ('h_vb_p', 'The Exile'), ('h_vb_d', 'The Brigand'), ('h_alliance_p', 'Spring Uprising'), ('h_alliance_d', 'Rabbit Scouts')], max_length=200, verbose_name='hirelings ter'),
        ),
        migrations.AddField(
            model_name='match',
            name='landmark_a',
            field=models.CharField(blank=True, choices=[('lm_bm', 'Black Mark'), ('lm_et', 'Elder Treetop'), ('lm_ferry', 'The Ferry'), ('lm_lf', 'Legendary Forge'), ('lm_lc', 'Lost City'), ('lm_tower', 'The Tower')], max_length=200, verbose_name='landmark'),
        ),
        migrations.AddField(
            model_name='match',
            name='landmark_b',
            field=models.CharField(blank=True, choices=[('lm_bm', 'Black Mark'), ('lm_et', 'Elder Treetop'), ('lm_ferry', 'The Ferry'), ('lm_lf', 'Legendary Forge'), ('lm_lc', 'Lost City'), ('lm_tower', 'The Tower')], max_length=200, verbose_name='landmark bis'),
        ),
    ]
