# Generated by Django 5.2.7 on 2025-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0042_match_hirelings_a_match_hirelings_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='deck',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('e&p', 'Exiles and Partisans')], max_length=200, verbose_name='deck'),
        ),
        migrations.AlterField(
            model_name='match',
            name='turn_timing',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('async', 'Async')], max_length=20, verbose_name='turn timing'),
        ),
    ]
