# Generated by Django 5.2.7 on 2025-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0043_alter_match_deck_alter_match_turn_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='landmark_a',
            field=models.CharField(blank=True, choices=[('lm_bm', 'Black Market'), ('lm_et', 'Elder Treetop'), ('lm_ferry', 'The Ferry'), ('lm_lf', 'Legendary Forge'), ('lm_lc', 'Lost City'), ('lm_tower', 'The Tower')], max_length=200, verbose_name='landmark'),
        ),
        migrations.AlterField(
            model_name='match',
            name='landmark_b',
            field=models.CharField(blank=True, choices=[('lm_bm', 'Black Market'), ('lm_et', 'Elder Treetop'), ('lm_ferry', 'The Ferry'), ('lm_lf', 'Legendary Forge'), ('lm_lc', 'Lost City'), ('lm_tower', 'The Tower')], max_length=200, verbose_name='landmark bis'),
        ),
    ]
