# Generated by Django 5.2.7 on 2025-12-21 11:49

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0044_alter_match_landmark_a_alter_match_landmark_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='landmarks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lm_bm', 'Black Market'), ('lm_et', 'Elder Treetop'), ('lm_ferry', 'The Ferry'), ('lm_lf', 'Legendary Forge'), ('lm_lc', 'Lost City'), ('lm_tower', 'The Tower')], max_length=200),
        ),
    ]
