# Generated by Django 5.2.7 on 2026-01-05 23:48

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0046_remove_match_hirelings_a_remove_match_hirelings_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='hirelings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('h_badgers_p', 'Vault Keepers'), ('h_badgers_d', 'Badger Bodyguards'), ('h_band_p', 'Popular Band'), ('h_band_d', 'Street Band'), ('h_bandits_p', 'Highway Bandits'), ('h_bandits_d', 'Bandit Gangs'), ('h_crows_p', 'Corvid Spies'), ('h_crows_d', 'Raven Sentries'), ('h_lizards_p', 'Warm Sun Prophets'), ('h_lizards_d', 'Lizard Envoys'), ('h_moles_p', 'Sunward Expedition'), ('h_moles_d', 'Mole Artisans'), ('h_birds_p', 'Last Dynasty'), ('h_birds_d', 'Bluebird Nobles'), ('h_cats_p', 'Forest Patrol'), ('h_cats_d', 'Feline Physicians'), ('h_protector_p', 'Furious Protector'), ('h_protector_d', 'Stoic Protector'), ('h_rats_p', 'Flame Bearers'), ('h_rats_d', 'Rat Smugglers'), ('h_otters_p', 'Riverfolk Flotilla'), ('h_otters_d', 'Otter Divers'), ('h_vb_p', 'The Exile'), ('h_vb_d', 'The Brigand'), ('h_alliance_p', 'Spring Uprising'), ('h_alliance_d', 'Rabbit Scouts')], max_length=200),
        ),
    ]
