# Generated by Django 6.0.2 on 2026-02-18 23:42

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0047_alter_match_hirelings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='hirelings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('h_badgers_p', 'Vault Keepers (P)'), ('h_badgers_d', 'Badger Bodyguards (D)'), ('h_band_p', 'Popular Band (P)'), ('h_band_d', 'Street Band (D)'), ('h_bandits_p', 'Highway Bandits (P)'), ('h_bandits_d', 'Bandit Gangs (D)'), ('h_crows_p', 'Corvid Spies (P)'), ('h_crows_d', 'Raven Sentries (D)'), ('h_lizards_p', 'Warm Sun Prophets (P)'), ('h_lizards_d', 'Lizard Envoys (D)'), ('h_moles_p', 'Sunward Expedition (P)'), ('h_moles_d', 'Mole Artisans (D)'), ('h_birds_p', 'Last Dynasty (P)'), ('h_birds_d', 'Bluebird Nobles (D)'), ('h_cats_p', 'Forest Patrol (P)'), ('h_cats_d', 'Feline Physicians (D)'), ('h_protector_p', 'Furious Protector (P)'), ('h_protector_d', 'Stoic Protector (D)'), ('h_rats_p', 'Flame Bearers (P)'), ('h_rats_d', 'Rat Smugglers (D)'), ('h_otters_p', 'Riverfolk Flotilla (P)'), ('h_otters_d', 'Otter Divers (D)'), ('h_vb_p', 'The Exile (P)'), ('h_vb_d', 'The Brigand (D)'), ('h_alliance_p', 'Spring Uprising (P)'), ('h_alliance_d', 'Rabbit Scouts (D)')], max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='turn_timing',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('async', 'Async')], help_text='Live games with <em>no timer</em> must be <strong>submitted as Live</strong>!', max_length=20, verbose_name='turn timing'),
        ),
    ]
