# Generated by Django 6.0.2 on 2026-08-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0048_alter_match_hirelings_alter_match_turn_timing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_closed', '-date_modified', '-date_registered'], 'permissions': [('drf_add_match', 'Can add matches through the DRF API'), ('drf_change_match', 'Can change matches through the DRF API'), ('drf_delete_match', 'Can delete matches through the DRF API')], 'verbose_name': 'match'},
        ),
    ]
