# Generated by Django 6.0.2 on 2026-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0049_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_void',
            field=models.BooleanField(default=False, verbose_name='void'),
        ),
    ]
