# Generated by Django 6.0.2 on 2026-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0050_match_is_void'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='turn_order',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True, verbose_name='turn order'),
        ),
    ]
