# Generated by Django 5.0.6 on 2024-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_player_first_name_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ig_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
