# Generated by Django 5.0.6 on 2024-07-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_player_ig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ig_id',
            new_name='in_game_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ig_name',
            new_name='in_game_name',
        ),
        migrations.AddField(
            model_name='player',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='players', to='authentification.role'),
        ),
    ]
