# Generated by Django 5.0.6 on 2024-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_role_rename_ig_id_player_in_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='in_game_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='In-game ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='In-game Username'),
        ),
    ]
