# Generated by Django 5.0.6 on 2024-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_alter_player_in_game_id_alter_player_in_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Discord Username'),
        ),
    ]
