# Generated by Django 5.0.6 on 2024-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_player_discord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='discord username'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='in-game ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='in-game Username'),
        ),
        migrations.AlterField(
            model_name='player',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='players', to='authentification.role', verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='role',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
