# Generated by Django 5.0.6 on 2024-07-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_alter_player_discord_name_alter_player_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
    ]
