# Generated by Django 5.0.6 on 2024-07-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_remove_player_first_name_remove_player_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
    ]
