# Generated by Django 5.1.1 on 2024-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_alter_player_discord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='discord username'),
        ),
    ]
