# Generated by Django 5.2.7 on 2026-01-28 21:15

import django.contrib.auth.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentification', '0013_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='Enter a valid Discord username. This value may contain only unaccented lowercase letters, numbers, and ./_ characters.', regex='^[a-z0-9._]+\\Z')], verbose_name='Discord username'),
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game_id',
            field=models.IntegerField(null=True, verbose_name='in-game ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(max_length=200, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='Enter a valid username. This value may contain only unaccented lowercase a-z and uppercase A-Z letters, numbers, and @/./-/_ characters.', regex='^[\\w.@-]+\\Z')], verbose_name='in-game username'),
        ),
        migrations.AlterConstraint(
            model_name='player',
            name='unique_in_game_id',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('in_game_name'), models.F('in_game_id'), name='unique_in_game_id', violation_error_message='A user with that ign+igid already exists.'),
        ),
    ]
