# Generated by Django 6.0.2 on 2026-09-20 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matchmaking', '0049_alter_match_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('timed_out', 'Timed out on purpose'), ('inappropriate_resign', 'Inappropriately resigned'), ('side_chat', 'Participated in private/side chats about game strategy'), ('broke_rule_to_void', 'Intentionally broke a league rule in order to void game'), ('submitted_void_result', 'Intentionally submitted a game result that was void'), ('ghosted', 'Participated in league game but did not register (i.e., ghosted)'), ('community_guidelines', 'Did not comply with the WW Community Guidelines'), ('submission_error', 'Match submission contains errors (details in description)'), ('other', 'Other')], max_length=30, verbose_name='reason')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10, verbose_name='status')),
                ('moderator_notes', models.TextField(blank=True, verbose_name='moderator notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='matchmaking.match', verbose_name='match')),
                ('reference_player', models.ForeignKey(blank=True, help_text='Player who can corroborate the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_in_reports', to=settings.AUTH_USER_MODEL, verbose_name='witness / reference player')),
                ('reported_player', models.ForeignKey(blank=True, help_text='Match participant, if registered. Leave empty for an unregistered player (but give their discord name in the description) or if the report is about submission errors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL, verbose_name='reported player')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='reports.report', verbose_name='report')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_player'], name='reports_rep_reporte_f805b5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['match'], name='reports_rep_match_i_e3041f_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportevidence',
            constraint=models.UniqueConstraint(fields=('report', 'url'), name='unique_evidence_url_per_report'),
        ),
    ]
