# Generated by Django 6.0.2 on 2026-10-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, help_text='Describe what happened. If the issue is about an unregistered player, state their discord name here.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_player',
            field=models.ForeignKey(blank=True, help_text='Match participant, if registered. Leave empty for an unregistered player or if the report is about submission errors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL, verbose_name='reported player'),
        ),
    ]
