# Generated by Django 5.2.7 on 2025-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='public',
            field=models.BooleanField(default=False, help_text='Public announcement (without log in)'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
