# Generated by Django 5.2.7 on 2025-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_announcement_public_announcement_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='public',
        ),
        migrations.AddField(
            model_name='announcement',
            name='registration_required',
            field=models.BooleanField(default=False, help_text='If this is checked, only logged-in users will be able to view the announcement.', verbose_name='registration required'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish',
            field=models.BooleanField(default=False, help_text='If this is checked, the announcement will be published.'),
        ),
    ]
