# Generated by Django 5.2.7 on 2025-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_remove_announcement_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='publish',
        ),
        migrations.AddField(
            model_name='announcement',
            name='published',
            field=models.BooleanField(default=False, help_text='If this is checked, the announcement will be published.', verbose_name='published'),
        ),
    ]
